command: ['python', 'app.py']
env:
  - name: 'DATABRICKS_WAREHOUSE_ID'
    value: '9cd919d96b11bf1c'
  - name: 'NODE_ENV'
    value: 'production'
resources:
  - name: sql-warehouse
    sql_warehouse:
      id: 9cd919d96b11bf1c
      permission: CAN_USE
  - name: serving-endpoint
    serving_endpoint:
      name: databricks-claude-sonnet-4
      permission: CAN_QUERY
